---
apiVersion: v1
kind: Namespace
metadata:
    name: influxdb
---   
kind: PersistentVolume
apiVersion: v1
metadata:
  name: influx-pv-volume
  namespace: influxdb
  labels:
    app: influx
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/"      
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influx-pv-claim
  namespace: influxdb
  labels:
    app: influx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
  namespace: influxdb
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
        - image: influxdb:1.8.3
          name: influx
          ports:
            - containerPort: 8086
              name: influx
          env:
            - name: INFLUXDB_DB
              value: sensor_data
            - name: INFLUXDB_USER
              value: fogguru
            - name: INFLUXDB_USER_PASSWORD
              value: FogGuru2020
          volumeMounts:
            - name: influx-pv
              mountPath: /var/lib/influxdb
              #mountPath: /root/.influxdbv2
      volumes:
        - name: influx-pv
          persistentVolumeClaim:
            claimName: influx-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: influx
  namespace: influxdb
  labels:
    app: influx
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: influx
  externalIPs:
  - 192.168.9.71
  - 172.20.192.19                  
