apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
spec:
  type: NodePort
  ports:
    - port: $port
      targetPort: 1880
  selector:
    app: nodered
  externalIPs:
  - $myclusterIP
