kind: PersistentVolume
apiVersion: v1
metadata:
  name: mosquitto-config-pv
  labels:
    app: mosquitto
    vol: config
  annotations:
    pv.beta.kubernetes.io/gid: "1"
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: mosquitto-gluster
    path: /mosquitto_volume
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-config-pvc
  labels:
    app: mosquitto	
    vol: config
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mosquitto-logs-pv
  labels:
    app: mosquitto
    vol: logs
  annotations:
    pv.beta.kubernetes.io/gid: "1"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: mosquitto-gluster
    path: /mosquitto_volume
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-logs-pvc
  labels:
    app: mosquitto
    vol: logs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mosquitto-data-pv
  labels:
    app: mosquitto
    vol: data
  annotations:
    pv.beta.kubernetes.io/gid: "1"
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: mosquitto-gluster
    path: /mosquitto_volume
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mosquitto-data-pvc
  labels:
    app: mosquitto
    vol: data
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
